Numpy Questions

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.
2. Find common elements between A and B. [Hint : Intersection of two sets]
3. Extract all numbers from A which are within a specific range. eg
between 5 and 10. [Hint: np.where() might be useful or boolean masks]
4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Pandas Questions
5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0).
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```
6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.
```
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
```
7. How to get the rows of a dataframe with row sum > 100?
```
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

In [6]:
import numpy as np
import pandas as pd

In [ ]:
#1.
a = np.array([[1,2],[3,8]])
b = np.array([[3,4],[2,4]])

print(np.vstack((a,b)))
print(np.hstack((a,b)))


[[1 2]
 [3 8]
 [3 4]
 [2 4]]
[[1 2 3 4]
 [3 8 2 4]]


In [ ]:
#2.
print(np.intersect1d(a,b))

[2 3]


In [ ]:
#3.
#Extract all numbers from A which are within a specific range. eg between 5 and
#10. [Hint: np.where() might be useful or boolean masks]

i = np.where((a>=5) & (a<=10))
print(a[i])

[8]


In [5]:
#4.
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filter_r = iris_2d[(iris_2d[:,2] > 1.5) & (iris_2d[:,0] < 5.0)]
print(filter_r)


[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


In [9]:
#5.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
filter_df = df[['Manufacturer', 'Model', 'Type']].iloc[::20]
print(filter_df)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


In [20]:
#6.
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')
#print(df.head())

mean_min = df['Min.Price'].mean()
mean_max = df['Max.Price'].mean()

df['Min.Price'].fillna(mean_min)
df['Max.Price'].fillna(mean_max)

miss = df[['Min.Price', 'Max.Price']].isnull().sum()
print(miss)


Min.Price    7
Max.Price    5
dtype: int64


In [21]:
#7.
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

filter_row = df[df.sum(axis=1) > 100]
#print(df)
print(filter_row)


     0   1   2   3
1   37  26  21  36
2   34  12  22  35
3   23  30  19  37
7   18  20  37  28
9   30  10  38  25
10  26  32  12  33
13  37  29  24  36
